### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by onlyfew** [QNJR-GROUP/sharding-method#1]
使用mac IntelliJ IDEA，导入项目后，编译失败。

`Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sharding-method: Compilation failure: Compilation failure:
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/sharding/ShardingRoutingDataSource.java:[11,50] 程序包org.springframework.jdbc.datasource.lookup不存在
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/sharding/ShardingRoutingDataSource.java:[18,48] 找不到符号
[ERROR] 符号: 类 AbstractRoutingDataSource
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/common/SpElHelper.java:[13,43] 程序包com.gs.collections.impl.map.mutable不存在
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/common/SpElHelper.java:[21,17] 找不到符号
[ERROR] 符号:   类 ConcurrentHashMap
[ERROR] 位置: 类 org.easydevelop.common.SpElHelper
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/mapreduce/strategy/provider/KeyValueMapReduceProvider.java:[7,43] 程序包com.gs.collections.impl.map.mutable不存在
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/common/ReflectHelper.java:[11,43] 程序包com.gs.collections.impl.map.mutable不存在
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/common/ReflectHelper.java:[20,24] 找不到符号
[ERROR] 符号:   类 ConcurrentHashMap
[ERROR] 位置: 类 org.easydevelop.common.ReflectHelper
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/sharding/ShardingRoutingDataSource.java:[48,17] 找不到符号
[ERROR] 符号:   变量 super
[ERROR] 位置: 类 org.easydevelop.sharding.ShardingRoutingDataSource
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/sharding/ShardingRoutingDataSource.java:[104,9] 方法不会覆盖或实现超类型的方法
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/sharding/ShardingRoutingDataSource.java:[109,9] 方法不会覆盖或实现超类型的方法
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/common/SpElHelper.java:[21,74] 找不到符号
[ERROR] 符号:   类 ConcurrentHashMap
[ERROR] 位置: 类 org.easydevelop.common.SpElHelper
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/mapreduce/strategy/provider/KeyValueMapReduceProvider.java:[32,24] 找不到符号
[ERROR] 符号:   类 ConcurrentHashMap
[ERROR] 位置: 类 org.easydevelop.mapreduce.strategy.provider.KeyValueMapReduceProvider
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/mapreduce/strategy/provider/KeyValueMapReduceProvider.java:[37,28] 找不到符号
[ERROR] 符号:   类 ConcurrentHashMap
[ERROR] 位置: 类 org.easydevelop.mapreduce.strategy.provider.KeyValueMapReduceProvider
[ERROR] /Users/zhan/Project/java/github/sharding-method/src/main/java/org/easydevelop/common/ReflectHelper.java:[20,99] 找不到符号
[ERROR] 符号:   类 ConcurrentHashMap
[ERROR] 位置: 类 org.easydevelop.common.ReflectHelper
[ERROR] -> [Help 1]`

**Comment by skyesx** [comment]
缺少的类都是Spring公共的包，可能是你的工程配置的问题，再检查一下？

**Comment by onlyfew** [comment]
谢谢，已解决
